sudo: required
dist: trusty # Ubuntu 14.04
services: docker # Enables docker
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: ./PDFfiles
  on:
    branch: master
script:
- cd ./EtaleI
- ../latexdockercmd.sh latexmk -pdf EtaleI.tex
- cd ../Fargues-Fontaine
- ../latexdockercmd.sh latexmk -pdf FF.tex
- cd ..
- mkdir PDFfiles
- cp ./EtaleI/EtaleI.pdf PDFfiles
- cp ./Fargues-Fontaine/FF.pdf PDFfiles
