sudo: required
dist: trusty # Ubuntu 14.04
services: docker # Enables docker
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./_build/
  on:
    branch: master
script:
- cd ./EtaleI
- ../latexdockercmd.sh latexmk -pdf -outdir=./_build EtaleI.tex
